### PR TITLE
Decode CodeSource-Path if not found.

### PR DESCRIPTION
**Pull request by kekru**
Hi, thanks for this great project, it helped us to set up integrative tests super fast and easily :)

When running our tests on Jenkins in a folder with an @-sign we found a problem:

When running tests in maven the command `clazz.getProtectionDomain().getCodeSource().getLocation()` inside TestConfigAnalyzer.java contains url-encoded parts. (when running from Intellij or eclipse it doesnt do)

e.g. if the CodeSource of the requested Class is in `/opt/abc@xyz/abc.jar` then it will return `/opt/abc%40xyz/abc.jar`, which is a file that cannot be found.
With this fix, if the file does not exist, we try to url-decode the path.

Before this fix, we had `new File("/opt/abc%40xyz/abc.jar")`.  
Then we called `file.toURI()` which again url-encodes the path to `/opt/abc%2540xyz/abc.jar`.

So we have a double-url-encoded path.

# Background
Our local maven repo has a @ sign in its path, which leads to a warning, that the deltaspike-jars could not be loaded (because of this `urlEncode(urlEncode(path))`) and finally no transactions could be
started, because deltaspike was not loaded.

# Running in a Test
```java
@Test
public void test() throws MalformedURLException {
	final File file = TestConfigAnalyzer.getCodeSourceLocation(DeltaSpike.class);
	System.out.println("New Version: " + file.getAbsolutePath());
	System.out.println("New Version: " + file.toURI().toURL());
	System.out.println("New Version file exists: " + file.exists());
	
	final File file2 = new File(DeltaSpike.class.getProtectionDomain().getCodeSource().getLocation().getPath());
	System.out.println("Old Version: " + file2.getAbsolutePath());
	System.out.println("Old Version: " + file2.toURI().toURL());
	System.out.println("Old Version file exists: " + file2.exists());
}
```

My local maven repo has an @-sign in its path, as defined in my settings.xml:
```xml
<settings...>
...
<localRepository>C:\Users\krummenauer\m2xy@2</localRepository>
</settings>
```

Running with
```bash
C:\Users\krummenauer\workspaceEJBCDIUnit\ejb-cdi-unit>mvn test -Dtest=ServiceTest -DfailIfNoTests=false
```

Output:
```bash
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.oneandone.ejbcdiunit.example7.ServiceTest
New Version: C:\Users\krummenauer\m2xy@2\org\apache\deltaspike\core\deltaspike-core-api\1.0.1\deltaspike-core-api-1.0.1.jar
New Version: file:/C:/Users/krummenauer/m2xy@2/org/apache/deltaspike/core/deltaspike-core-api/1.0.1/deltaspike-core-api-1.0.1.jar
New Version file exists: true
Old Version: C:\Users\krummenauer\m2xy%402\org\apache\deltaspike\core\deltaspike-core-api\1.0.1\deltaspike-core-api-1.0.1.jar
Old Version: file:/C:/Users/krummenauer/m2xy%25402/org/apache/deltaspike/core/deltaspike-core-api/1.0.1/deltaspike-core-api-1.0.1.jar
Old Version file exists: false
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.342 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

### CODE REVIEW

**Comment by aschoerk** [comment]
Thank you very much for the effort. 
I changed the solution somewhat, could you have a look, if "https://github.com/1and1/ejb-cdi-unit/commit/c8c9487b3d92132ea24e3e12b50745c29d36b474" is also effective at your site?
The main problem seems to be a faulty version of reflections, the update to the current version helps.

**Comment by kekru** [comment]
Thanks for your quick reply :)

Your fix seems to work for us, too. 
Is it already available in any public maven repo as snapshot?  
Or do you already know, when you release the next version in a public maven repo?

**Comment by kekru** [comment]
I close this pullrequest, because the problem was fixed in c8c9487b3d92132ea24e3e12b50745c29d36b474

**Comment by aschoerk** [comment]
Hello Kevin,

at the moment I try to fix the existing issue.

 


Next Release on Maven Centra will come this weekend.

 

Greetings

Andreas


Gesendet: Freitag, 13. April 2018 um 10:41 Uhr
Von: "Kevin Krummenauer" <notifications@github.com>
An: 1and1/ejb-cdi-unit <ejb-cdi-unit@noreply.github.com>
Cc: "Andreas Schörk" <aschoerk@gmx.net>, Comment <comment@noreply.github.com>
Betreff: Re: [1and1/ejb-cdi-unit] Decode CodeSource-Path if not found. (#3)


Thanks for your quick reply :)

Your fix seems to work for us, too.
Is it already available in any public maven repo as snapshot?
Or do you already know, when you release the next version in a public maven repo?

**Comment by kekru** [comment]
Thank you :+1: That was fast :)

**Pull request closed without merging**
